### ISSUE TITLE
"-":0: bad minute

### ISSUE THREAD

**Issue by TOTOleHero** [renskiy/cron-docker-image#5]
hello,

We need to use your container with kubernetes.

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cron-project
  name: cron-project
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cron-project
    spec:
      containers:
      - image: renskiy/cron:debian 
        command: ["start-cron"]
        args:
          - "--user"
          - "www-data"
          - '"\*/2 \* \* \* \* env >> /logs/project-cron.log 2>&1"'
        name: project
      restartPolicy: Always

```

When i deploy this we have error ; 

```
"-":0: bad minute
errors in crontab file, can't install.
Starting periodic command scheduler: cron.
```
